module.exports = [
  '/bower_components/PACE/pace.min.js',
  '/js/jquery.js',
  '/js/modernizr.js',
  '/js/perfect-scrollbar.js',

  '/js/l20n.js',

  "/js/vendor/prism/prism.js",
  "/js/vendor/select2/select2.js",
  '/js/vendor/timeline/timeline.js',
  "/js/vendor/ion.rangeSlider/ion.rangeSlider.js",

  '/bower_components/d3/d3.js',
  "/bower_components/c3/c3.js",
  '/bower_components/Chart.js/Chart.js',
  '/bower_components/gmaps/gmaps.min.js',
  "/bower_components/raphael/raphael.min.js",
  "/bower_components/morris.js/morris.min.js",
  "/bower_components/leaflet/dist/leaflet.js",
  '/bower_components/moment/min/moment.min.js',
  "/bower_components/dropzone/dist/dropzone.js",
  "/bower_components/seiyria-bootstrap-slider/dist/bootstrap-slider.min.js",
  "/bower_components/jquery-ui/jquery-ui.min.js",
  '/bower_components/vex/js/vex.combined.min.js',
  "/bower_components/codemirror/lib/codemirror.js",
  '/bower_components/trumbowyg/dist/trumbowyg.min.js',
  "/bower_components/switchery/dist/switchery.min.js",
  "/bower_components/filament-tablesaw/dist/tablesaw.js",
  "/bower_components/bootstrap-sass/assets/javascripts/bootstrap/transition.js",
  "/bower_components/bootstrap-sass/assets/javascripts/bootstrap/collapse.js",
  "/bower_components/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js",
  "/bower_components/bootstrap-sass/assets/javascripts/bootstrap/popover.js",
  "/bower_components/messenger/build/js/messenger.min.js",
  "/bower_components/jquery-knob/dist/jquery.knob.min.js",
  "/bower_components/blueimp-gallery/js/blueimp-gallery.js",
  "/bower_components/jquery.steps/build/jquery.steps.min.js",
  "/bower_components/codemirror/mode/javascript/javascript.js",
  "/bower_components/typeahead.js/dist/typeahead.jquery.min.js",
  "/bower_components/jquery-validation/dist/jquery.validate.min.js",
  '/bower_components/kapusta-jquery.sparkline/dist/jquery.sparkline.js',
  "/bower_components/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.js",
  "/bower_components/x-editable/dist/inputs-ext/address/address.js",
  "/bower_components/x-editable/dist/inputs-ext/typeaheadjs/typeaheadjs.js",
  '/bower_components/eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js',
  "/bower_components/datatables/media/js/jquery.dataTables.js",
  "/js/vendor/fullcalendar/fullcalendar.js",
  "/js/vendor/datatables/responsive.js",
  "/js/vendor/jcrop/color.js",
  "/js/vendor/jcrop/jcrop.js",

  '/js/rubix.js',
];
